# Generated by Django 4.2 on 2023-05-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=4096)),
                ('variant_a', models.CharField(max_length=4096)),
                ('variant_b', models.CharField(max_length=4096)),
                ('variant_c', models.CharField(max_length=4096)),
                ('variant_d', models.CharField(max_length=4096)),
                ('correct_answer', models.IntegerField()),
            ],
        ),
    ]
